kickpro/kickpro/urls.py
from django.contrib import admin
from django.urls import path,include
from project.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/',include('project.urls')),
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('user/myprofile',UserProfile,name='user_profile'),
    path('user/<int:user_id>/',publicProfile,name='user_PublicProfile'),
    path('search/<slug:searchText>/',search,name='search'),
    path('discover',Discover,name='discover'),
    path('login/',user_login,name='login'),
    path('sign_up/',register,name='sign_up'),
    path('index/',index,name='index'),
    path('logout/',auth_views.LogoutView.as_view(template_name='home.html'),name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

kickpro/project/urls.py
from . views import *

from django.urls import path,include


urlpatterns = [
    path('new/',newProject,name='new_project'),
    path('view/<int:project_id>/', singleProject, name='view_project'),
    # path('comments/<int:project_id>/', comments, name='view_comments'),
    path('reportcomment/<int:id>/', report_comment, name='reportcomment'),
    path('reportproject/<int:id>/', report_project, name='reportproject'),
]

kickpro/project/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.core.validators import RegexValidator
from taggit.managers import TaggableManager  ##TAGS



######USER######
################

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    FullName = models.CharField(max_length=50)
    portfolio_site = models.URLField(blank=True)
    BirthDate = models.DateField()
    mobile = models.CharField(max_length=11, validators=[RegexValidator(regex='^01[0|1|2|5][0-9]{8}')])
    Country = CountryField()
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True,default='profile_pics/nopic.jpeg')

    def __str__(self):
        return self.FullName





class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# class Tag(models.Model):
#     name = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name




####PROJECT#####
################

class Project(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    current = models.IntegerField(default=0)
    target = models.IntegerField(default=100)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # tags = models.ManyToManyField(Tag, related_name="projects")
    tags = TaggableManager()
    date_lastupdated = models.DateField(auto_now=True)
    date_added = models.DateField(auto_now_add=True)
    main_pic = models.ImageField(upload_to='projects_pics', blank=True,default='projects_pics/default.jpg')
    featuredCHOICE = (
        ('1', 'Yes'),
        ('0', 'No'),
    )
    featured_project = models.CharField(max_length=1, choices=featuredCHOICE,default=0)

    def __str__(self):
        return self.title


class Project_Images(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    project_img = models.ImageField(upload_to='multi', blank=True, default='projects_pics/nopic.jpeg')





def get_avg_rate(self):
    return self.rate_set.all().aggregate(models.Avg("value"))


def get_total_donations(self):
    return self.donation_set.all().aggregate(models.Sum("value"))


def get_rates_count(self):
    return self.rate_set.all().count()


def get_donations_count(self):
    return self.donation_set.all().count()


def is_cancelable(self):
    return self.get_total_donations() <= 0.25 * self.target


class Donations(models.Model):
    amount = models.IntegerField()
    donation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.user


class Rating(models.Model):
    rate = models.IntegerField(choices=[(str(i), str(i)) for i in range(6)])
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.user


class Featured(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.project


class Comments(models.Model):
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    comment = models.TextField()
    # date = models.DateField(auto_now= True, blank= True)


class commentReport(models.Model):
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add= True)
    subject = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return self.subject

        

class projectReport(models.Model):
    user = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add= True)
    subject = models.CharField(max_length=100)
    details = models.TextField()

    def __str__(self):
        return self.subject

kickpro/project/forms.py
from django.forms import forms, ModelForm
from .models import *

# dappx/forms.py
from django import forms
from django.db import models
from .models import UserProfileInfo
from django.contrib.auth.models import User
# from models import ModelForm
from django.forms.models import modelformset_factory
from django.forms import inlineformset_factory
# from django.forms import SharingForms
# from .models import Images
from taggit.managers import TaggableManager

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('FullName', 'portfolio_site', 'profile_pic', 'BirthDate', 'mobile', 'Country')




class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'details', 'target', 'start_date', 'end_date', 'user', 'category', 'tags', 'main_pic']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']


class CommentReport(forms.ModelForm):
    class Meta:
        model = commentReport
        fields = ['subject', 'details']


class ReportProject(forms.ModelForm):
    class Meta:
        model = projectReport
        fields = ['subject', 'details']

kickpro/project/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from pprint import pprint
from django.db.models import Q

from .models import *
from .forms import *
from django.http import HttpResponse
# from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.forms import modelformset_factory
from django.forms import inlineformset_factory

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.shortcuts import render_to_response
from django.template import RequestContext


###### Sha'lan Edit ####

########Registration with Confirmation#######
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            user.is_active = False
            user.set_password(user.password)
            user.save()
            # profile = profile_form.save(commit=False)
            # user.is_active = False
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            # registered = True
            #######CONFIRMATION##########
            current_site = get_current_site(request)
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })

            mail_subject = 'Activate your KickPro account.'
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
            ######################################
            ######################################
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


##########################################
##########################################
######Activation Function#################
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist()):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # profile.save()
        # registered = True
        login(request, user)

        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        # return redirect('home')
    else:
        return HttpResponse('Activation link is invalid or Expired!')


def index(request):
    return render(request,'index.html')
@login_required(login_url='/#login')
def special(request):
    return HttpResponse("You are logged in !")
@login_required(login_url='/#login')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

# def register(request):
#     registered = False
#     if request.method == 'POST':
#         user_form = UserForm(data=request.POST)
#         profile_form = UserProfileInfoForm(data=request.POST)
#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             user.set_password(user.password)
#             user.save()
#             profile = profile_form.save(commit=False)
#             profile.user = user
#             if 'profile_pic' in request.FILES:
#                 print('found it')
#                 profile.profile_pic = request.FILES['profile_pic']
#             profile.save()
#             registered = True
#         else:
#             print(user_form.errors,profile_form.errors)
#     else:
#         user_form = UserForm()
#         profile_form = UserProfileInfoForm()
#     return render(request,'registration.html',
#                           {'user_form':user_form,
#                            'profile_form':profile_form,
#                            'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})

###### Hossam Edit #####


def search(request):
    searchText = request.POST['searchText']
    print(searchText)
    Projects = Project.objects.filter(title__icontains =searchText)

    context = {'projects':Projects,'word':searchText}
    return render(request,'search.html',context)



def home(request):

    PopularProjects = Project.objects.order_by('current').reverse()[:4]
    Top5 = Project.objects.order_by('current').reverse()[:5]
    featuredProjects = Project.objects.filter(featured_project =1)
    Cats = Category.objects.all()
    context = {'popular':PopularProjects,'featured':featuredProjects,'cats':Cats,'top':Top5}
    return render(request,'home.html',context)

# def register(request):
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#
#         if form.is_valid():
#
#             form.save()
#             return HttpResponse('Done')
#         else:
#             return HttpResponse('Validation Error !')
#
#     else:
#         form = RegisterForm()
#         return render(request,'register.html',{'form':form})

#User Add Project Form
@login_required(login_url='/#login')
def newProject(request):
    ImageFormSet = modelformset_factory(Project_Images, fields=('project_img',), extra=2)

    if request.method == 'POST':
        PostRequest = request.POST.copy()
        print('testing ####')
        print(request.session['_auth_user_id'])
        PostRequest['user'] = request.session['_auth_user_id']
        form = CreateProjectForm(PostRequest)
        formset = ImageFormSet(PostRequest, request.FILES)

        print(PostRequest)
        if form.is_valid() and formset.is_valid():
            post_form = form.save(commit=False)
            post_form.user = request.user.userprofileinfo
            if 'main_pic' in request.FILES:
                print('found it')
                post_form.main_pic = request.FILES['main_pic']
            post_form.save()
            form.save_m2m()
            #####JO
            for pic in formset:
                try:
                    picture = Project_Images(project_img=pic.cleaned_data['project_img'], project= post_form)
                    picture.save()
                except Exception as e:
                    break


            

            return HttpResponse('Project Created')
        else:
            return render(request, 'new_project.html', {'form': form, 'form_errors': form.errors})
            # print(form.errors)
            # return HttpResponse('Validation Failed!')
    else:
        form = CreateProjectForm()
        formset = ImageFormSet(queryset=Project_Images.objects.none())
        # return render(request,'new_project.html',{'form':form})
        return render(request, 'new_project.html',
                      {'form': form, 'formset': formset})

@login_required(login_url='/#login')
#User Profile
def UserProfile(request):
    if(request.method == 'POST'):

        form = UserProfileInfoForm(request.POST)
        if form.is_valid():
            PostRequest = request.POST
            User_ID =request.user
            user = UserProfileInfo.objects.get(user=User_ID)
            Postform = UserProfileInfoForm(PostRequest, instance=user)
            print(PostRequest)
            Postform.save()
            return HttpResponse('Data updated')

        else:
            return HttpResponse('Validation Failed!')

    else:
        form = UserProfileInfoForm()
        User_Projects = Project.objects.filter(user=request.user.userprofileinfo)
        context = {'User_Projects':User_Projects,'form':form}
        return render(request, 'user_profile.html',context)



#Discover Section
def Discover(request):
    All_Projects = Project.objects.all()

    Projects_Num = len(All_Projects)
    All_Cats = Category.objects.all()
    #Today_Date = datetime.datetime.today().strftime('%Y-%m-%d')

    context = {'projects':All_Projects,'Projects_Num':Projects_Num,'Cats':All_Cats}

    return render(request, 'discover.html',context)

#Single Project Section
def singleProject(request,project_id):

    Single_Project = Project.objects.get(id=project_id)

kickpro/project/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

kickpro/project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'login' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'sign_up' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

kickpro/project/templates/discover.html
{% extends 'layout.html' %}

{% block content %}


    <div class="layout-2cols">
        <div class="content grid_9">
            <div class="search-result-page">
                <div class="top-lbl-val">
                    <h3 class="common-title">Discover  <span class="fc-orange">Amazing Projects</span></h3>
                    <div class="count-result">
                        <span class="fw-b fc-black">{{Projects_Num}}</span> projects found in this category
                    </div>
                </div>
                <div class="list-project-in-category">
                    <div class="lbl-type clearfix">
                        <a href="#" class="view-all be-fc-orange">View all</a>
                    </div>
                    <div class="list-project">
                        {% for key in projects %}
                        <div class="grid_3">
                            <div class="project-short sml-thumb">
                                <div class="top-project-info">
                                    <div class="content-info-short clearfix">
                                        <a href="/project/view/{{key.id}}" class="thumb-img">
                                            <img src="{{key.main_pic.url}}" alt="$TITLE">
                                        </a>
                                        <div class="wrap-short-detail">
                                            <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">{{key.title}}</a></h3>
                                            <p class="rs tiny-desc">by <a href="/user/{{key.user.id}}" class="fw-b fc-gray be-fc-orange">{{key.user}}</a></p>
                                            <p class="rs title-description">{{key.details}}</p>

                                        </div>
                                    </div>
                                </div>
                                <div class="bottom-project-info clearfix">
                                    <div class="line-progress">
                                        <div class="bg-progress">
                                            <span id="progress_bar"  style="width: calc({{key.current}}%/{{key.target}}*100)"></span>
                                        </div>
                                    </div>
                                    <div class="group-fee clearfix">
                                        <div class="fee-item">
                                            <p class="rs lbl">Funded</p>
                                            <span class="val"><script>document.write({{key.current}}/{{key.target}}*100);</script>%</span>
                                        </div>
                                        <div class="sep"></div>
                                        <div class="fee-item">
                                            <p class="rs lbl">Pledged</p>
                                            <span class="val">{{key.current}}$</span>
                                        </div>
                                        <div class="sep"></div>
                                        <div class="fee-item">
                                            <p class="rs lbl">Days left</p>
                                            <span class="val" style="font-size: 11px; color: red;">{{key.end_date|timeuntil }} </span>

                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div><!--end: .grid_3 > .project-short-->
                        {% if key.id|divisibleby:3 %}
                        <div class="clear"></div>
                        {% endif %}
                        {% endfor %}

                        <div class="clear"></div>
                    </div>
                </div><!--end: .list-project-in-category -->
                <p class="rs ta-c">
                    <a id="showmoreproject" class="btn btn-black btn-load-more" href="#">Show more projects</a>
                </p>
            </div><!--end: .search-result-page -->
        </div><!--end: .content -->
        <div class="sidebar grid_3">
            <div class="left-list-category">
                <h4 class="rs title-nav">Category</h4>
                <ul class="rs nav nav-category">
                    <li class="active">
                        <a href="#">
                            All
                            <span class="count-val">({{Projects_Num}})</span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    {% for cat in Cats%}
                    <li >
                        <a href="#">
                            {{cat.name}}
                            <span class="count-val"></span>
                            <i class="icon iPlugGray"></i>
                        </a>
                    </li>
                    {% endfor %}

                </ul>
            </div><!--end: .left-list-category -->
        </div><!--end: .sidebar -->
        <div class="clear"></div>
    </div>



{% endblock %}

kickpro/project/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

kickpro/project/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

kickpro/project/templates/register.html
{% extends 'layout.html' %}

{% block content %}



{% endblock %}

kickpro/project/templates/report.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}

 <div class="form form-profile" style="margin: 0 auto;">
    


        <h1>SORRY!</h1>
        <h3>Please, Let's know what is the problem:</h3>
   <div class="tab-content" style="width: 110%;">
    <div>
        <h3 class="rs alternate-tab accordion-label">Never Mind..</h3>
        <div class="tab-pane accordion-content active">
            <div class="form form-profile" >


                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}

                      <p><label for="subject">Subject:</label> <input type="text" class="txt fill-width" name="subject" maxlength="150" required="" id="id_subject">
                  <span class="helptext">Required. 150 characters or fewer. Give us short hint about the problem..</span></p>
              
              <p><label for="id_details">Details:</label> <input type="text" name="details" class="txt fill-width" maxlength="50" required="" id="id_details"></p>
                    <input type="submit" name="" class="txt fill-width" value="Report">
                  </form>
            </div>
        </div><!--end: .tab-pane -->
        <br>
    </div>

    <div>

    </div>

    </div>
 </div>

{% endblock %}

kickpro/project/templates/search.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}

 <div class="layout-2cols">
        <div class="content grid_9">
            <div class="search-result-page">
                <div class="top-lbl-val">
                    <h3 class="common-title">Discover / <span class="fc-orange">Search for {{word}}</span></h3>
                    <div class="count-result">
                        Projects found for “<span class="fw-b fc-black">{{word}}</span>”
                    </div>
                </div>
                <div id="list-search-ajax" class="list-project-result">
            {% for project in projects %}
                    <div class="project-short larger">
                        <div class="top-project-info">
                            <div class="content-info-short clearfix">
                                <a href="/project/view/{{project.id}}" class="thumb-img">
                                    <img src="{{project.main_pic.url}}" alt="">
                                </a>
                                <div class="wrap-short-detail">
                                    <h3 class="rs acticle-title"><a class="be-fc-orange" href="#">{{project.title}}</a></h3>
                                    <p class="rs tiny-desc">by <a href="#" class="fw-b fc-gray be-fc-orange">{{project.user}}</a>
                                    <p class="rs title-description">{{project.details}}</p>

                                </div>

                            </div>
                        </div><!--end: .top-project-info -->
                        <div class="bottom-project-info clearfix">
                            <div class="project-progress sys_circle_progress" data-percent="{% widthratio project.current project.target 100 %}">
                                <div class="sys_holder_sector"></div>
                            </div>
                            <div class="group-fee clearfix">

                                <div class="fee-item">
                                    <p class="rs lbl">Pledged</p>
                                    <span class="val">${{project.current}}</span>
                                </div>
                                <div class="sep"></div>
                                <div class="fee-item">
                                    <p class="rs lbl">Time Left</p>
                                    <span class="val">{{project.end_date|timeuntil }}</span>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div><!--end: project-short item -->
            {% endfor %}
                </div>

            </div><!--end: .search-result-page -->
        </div><!--end: .content -->

        <div class="clear"></div>
    </div>

{% endblock %}

kickpro/project/templates/single_user.html
{% extends 'layout.html' %}

{% block content %}

<div class="layout-2cols">
        <div class="content grid_12">
            <div class="single-page">
<div name="user_info" style="margin:0 auto;text-align: center;">
                    <img style="width: auto;height: 195px;border-radius: 125px;" src="{{PublicUser.userprofileinfo.profile_pic.url}}">
                <h2 class="rs single-title">{{PublicUser.userprofileinfo.FullName}}</h2>
</div>


            </div>
        </div><!--end: .content -->
        <div class="clear"></div>
    </div>

    <div class="additional-info-line">
        <div class="container_12" >

            <div class="grid_1 ta-r" style="text-align:center;">
            <h2 style=" color: #ea513d;">Country</h2>
              <p class="rs" ><img style="width: 68px;" alt="{{PublicUser.userprofileinfo.Country}}" src="/static/images/flag/{{PublicUser.userprofileinfo.Country|lower}}.png"></p>
            </div>
                        <div class="grid_3 ta-r" style="text-align:center;">
            <h2 style=" color: #ea513d;">Projects</h2>
            <h1>{{NumProjects}}</h1>
            </div>
            <div class="grid_4 ta-r" style="text-align:center;">
            <h2 style=" color: #ea513d;">Last Active</h2>
            <h2>{{PublicUser.last_login|timesince}}</h2>
            </div>
            <div class="grid_4 ta-r" style="text-align:center;">
            <h2 style=" color: #ea513d;">Joined</h2>
            <h2>{{PublicUser.date_joined}}</h2>
            </div>
            <div class="clear"></div>

        </div>
    </div><!--end: .additional-info-line -->

{% endblock %}